import { StyleSheet, Platform } from 'react-native'
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen'
import Colors from '../Colors'

export default StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
  },
  secondContainer: {
    backgroundColor: 'white',
    width: wp('96%'),
    marginTop: hp('.5%'),
    borderRadius: 5,
  },
  scrollview: {
    marginLeft: 10,
    marginTop: 10,
    backgroundColor: '#ffffff',
  },
  postContainer: {
    backgroundColor: '#ffffff',
    marginTop: 20,
    height: hp('92%'),
  },
  topPostContainer: {
    backgroundColor: '#ffffff',
    marginTop: hp('1%'),
  },
  post: {
    backgroundColor: '#ffffff',
    height: hp('19.6%'),
    borderEndColor: '#f0f0f0',
    borderBottomWidth: 0.25,
    flexDirection: 'row',
  },
  tribePill: {
    borderRadius: wp('.6%'),
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('2.6%'),
    marginTop: Platform.OS === 'ios' ? null : hp('1.5%'),
  },
  pillText: {
    fontSize: 12,
    fontWeight: 'bold',
    margin: 5,
  },
  leftColumn: {
    marginTop: 15,
    marginRight: 6,
    marginLeft: 6,
    alignItems: 'center',
  },
  rightColumn: {
    width: wp('83.4%'),
    marginTop: 10,
  },
  userInfo: {
    height: 35,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 8,
  },
  nameHolder: {
    marginLeft: wp('1.3%'),
  },
  settings: {
    position: 'absolute',
    marginLeft: wp('77%'),
  },
  commentBox: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('1.5%'),
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  postTitleContainer: {
    marginTop: hp('1.5%'),
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  postTitle: {
    fontSize: 14,
    color: '#000000',
    fontWeight: 'bold',
    textAlign: 'left',
    height: 52,
  },
  image: {
    width: 91,
    height: 61,
  },
  titleHolder: {
    width: 190,
    marginLeft: 14,
  },
  tribeText: {
    fontSize: 10,
    letterSpacing: 1,
    color: '#00BEAB',
    fontWeight: '600',
    marginBottom: 1,
    textTransform: 'uppercase',
  },
  postText: {
    fontSize: 12,
    color: '#000000',
    fontWeight: '600',
  },
  bottomContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 10,
  },
  iconContainer: {
    flexDirection: 'row',
    position: 'absolute',
    marginLeft: 230,
  },
  badge: {
    height: 13,
    width: 25,
    backgroundColor: '#333333',
    marginLeft: 5,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 1,
  },
  badgeText: {
    fontSize: 9,
    color: 'white',
  },
  authorText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  timeText: {
    fontSize: 12,
    color: '#999999',
  },
  voteText: {
    fontSize: 12,
    color: '#555555',
    fontWeight: '600',
  },
  commentNumberText: {
    fontSize: 12,
    color: '#000000',
    marginLeft: 7,
  },
  bookmark: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginRight: wp('38%'),
  },
  share: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginRight: wp('4%'),
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  loaderBlue: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#b6cefc',
  },
  card: {
    width: wp('43.8%'),
    height: hp('32.23%'),
    backgroundColor: '#333333',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  tribeNameText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: 'bold',
    marginTop: 20,
  },
  cardIcon: {
    marginTop: 20,
  },
  memberNumberText: {
    fontSize: 12,
    color: '#999999',
    marginTop: 8,
  },
  followText: {
    fontSize: 10,
    color: '#ffffff',
    fontWeight: 'bold',
    marginTop: 4,
    letterSpacing: 3,
    marginTop: 20,
  },
  line: {
    backgroundColor: '#555555',
    height: 1,
    width: wp('43.8%'),
    marginTop: 20,
  },
  whiteCard: {
    width: wp('43.8%'),
    height: hp('32.23%'),
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    borderColor: '#555555',
    borderWidth: 0.3,
  },
  blackTribeNameText: {
    fontSize: 14,
    color: '#000000',
    fontWeight: 'bold',
    marginTop: 20,
  },
  blackCardWrapper: {
    marginTop: 20,
    color: '#000000',
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  blackFollowText: {
    fontSize: 10,
    color: '#000000',
    fontWeight: 'bold',
    marginTop: 4,
    letterSpacing: 3,
    marginTop: 20,
  },
  disCoverBox: {
    height: 59,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  discoverText: {
    fontSize: 18,
    color: '#000000',
    fontWeight: 'bold',
    marginLeft: 10,
  },
  menu: {
    marginTop: 15,
    marginLeft: 5,
  },
  menuOption: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'red',
    width: 177,
    height: 255,
  },
  menuOptionText: {
    fontSize: 14,
    color: '#000000',
    marginLeft: 5,
  },
  separator: {
    width: wp('96%'),
    height: hp('.2%'),
    backgroundColor: '#f0f0f0',
  },
  modal: {
    backgroundColor: 'white',
    marginTop: hp('3%'),
  },
  modalHeading: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    marginTop: hp('3%'),
    marginLeft: wp('4%'),
    marginBottom: hp('3%'),
  },
  modalReasonText: {
    fontSize: 13,
    fontWeight: '600',
    marginLeft: wp('4%'),
  },
  dropContainer: {
    width: wp('70%'),
    marginLeft: wp('4%'),
  },
  secondModalReasonText: {
    fontSize: 13,
    fontWeight: '600',
    marginLeft: wp('4%'),
    marginTop: hp('2.25%'),
  },
  modalInput: {
    width: wp('70%'),
    height: hp('20%'),
    borderRadius: wp('1%'),
    borderWidth: wp('.1%'),
    borderColor: '#E0E0E0',
    marginLeft: wp('4%'),
    marginTop: hp('1%'),
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginRight: wp('5.8%'),
    marginTop: hp('2.5%'),
  },
  button: {
    backgroundColor: 'black',
    width: 120,
    height: 35,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttontext: {
    fontSize: 13,
    fontWeight: '600',
    color: 'white',
  },
  modalCancelText: {
    color: '#999999',
    marginRight: 10,
  },
  cardContainer: {
    alignItems: 'center',
    backgroundColor: Colors.primary,
    width: wp('100'),
    height: hp('150%'),
    marginRight: wp('10%'),
  },
  postCreateCard: {
    width: wp('95.7'),
    height: hp('110%'),
    backgroundColor: '#FFFFFF',
    paddingLeft: wp('3.2%'),
    paddingTop: hp('2.9%'),
    paddingRight: wp('6.4%'),
  },
  titleText: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: wp('.6%'),
    marginBottom: hp('2.9%'),
  },
  tagTitleText: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: wp('.6%'),
    marginBottom: hp('2.2%'),
  },
  textInput: {
    borderBottomWidth: 0.4,
    borderColor: 'grey',
    paddingBottom: 10,
    marginBottom: hp('1.79%'),
  },
  gap: {
    height: hp('5.84%'),
  },
  input: {
    borderBottomWidth: 1.5,
    borderColor: '#F0F0F0',
  },

  buttonSmall: {
    padding: 5,
    height: 40,
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    borderRadius: 3,
  },
  buttontext: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
  },
  tag: {
    backgroundColor: 'black',
    borderRadius: 10,
    height: 20,
  },
  tagContainer: {
    borderBottomWidth: 0.4,
    borderColor: 'grey',
  },
  tagText: {
    color: 'white',
  },
  tagText: {
    color: 'white',
  },
  searchTagContainer: {
    flexDirection: 'row',
  },
  searchTag: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    height: 20,
    backgroundColor: 'black',
    marginRight: 5,
  },
  searchTagText: {
    color: 'white',
    fontSize: 10,
    paddingHorizontal: 5,
    fontWeight: 'bold',
  },
  bigButton: {
    width: 315,
    height: 60,
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    borderRadius: 3,
    marginTop: hp('4.5%'),
    marginBottom: hp('4%'),
  },
  horizontalGap: {
    width: 5,
  },
  photoUploader: {
    backgroundColor: 'black',
    width: wp('35%'),
    height: hp('7%'),
    borderRadius: hp('3.5%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: hp('3%'),
  },
  headerForModal: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    width: wp('100%'),
    height: hp('9%'),
    alignItems: 'center',
    paddingTop: 10,
    paddingLeft: 5,
  },
})
